author:
  name: Wenjie Ruan
baseURL: https://blog.wuhanstudio.cn
languageCode: en
menu:
  main:
    - name: Projects
      url: /projects
    - name: Blog
      url: /blog
params:
  description: Exeter Trustworthy AI Lab (ETAL)
title: TrustAI
theme: Blogpaper
