author:
  name: Wenjie Ruan
baseURL: https://blog.wuhanstudo.cn
languageCode: en
menu:
  main:
    - name: Projects
      url: /projects
    - name: Blog
      url: /blog
params:
  description: Example site for the Hugo's Blogpaper theme
title: TrustAI
theme: Blogpaper
